"""Initial Migration

Revision ID: 082aaca170ae
Revises: 7502984d7341
Create Date: 2018-02-09 03:25:50.333965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082aaca170ae'
down_revision = '7502984d7341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availablepizzas', sa.Column('img_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('availablepizzas', 'img_url')
    # ### end Alembic commands ###
